package myclassproject.mystorygraph;

//Fill this enum with the labels you chose for the EDGES of your story graph.
public enum MyChoiceLabels {
	StartGameEdges,
	rootEdges,
	atCityEdges,
	gotoBarrell,
	gotoMerchantBill,
	PickUpApple,
	WalkToFountain,
	TalkToBeggar,
	WalkToMerchantBill, 
	TalkToMerchantBill,
	gotoForesstPath,
	ContinueDrinkingChoice,
	GoToFireplaceChoice,
	VisitTavernTableChoice,
	BurnedToDeathChoice,
	PickupTorchChoice,
	GoToBarrell,
	GoToMerchantBill,
	WalkToForest,
	InteractWithForestPlant, 
	WalkToForestWell, 
	InteractWithBarrell, 
	InteractWithBeggar, 
	EnterForest, 
	InteractWithWell, 
	InteractWithBandit,
	ReturnToMerchant,
	InteractWithMerchant, 
	InteractWithDungeonDoor, 
	NoSwordInteractWithBandit,   
	WalkToTavern, 
	SitInTavern,
	WalkToDrunkard,
	IgnoreDrunkard,
	TalkToDrunkard,
	TalkingToDrunkard,WakeUpDrunkard,
	WakeDrunkard,
	RobDrunkard,
	LeaveDrunkard,
	PersistDrunkard,
	GoToBar,
	BuyDrink,
	LeaveTavern,
	DrunkardDoor,
	MerchantKillTalk,
	PickUpBag, ReturnToCity
	
	
	
}
