package myclassproject.mystorygraph;

//Fill this enum with the labels you chose for the NODES of your story graph.
public enum MyNodeLabels{
	root, 
	atCottage,  
	accept2, 
	refuse, 
	inventory, 
	atCity, 
	atCity2, 
	banditTalk, 
	reset, 
	startGame, 
	StartGame, 
	merchantbillTalk, 
	atForestPath,
	well,
	BanditSword, 
	KillBandit,
	Barrell, 
	Fountain, 
	FountainYes, 
	TavernActions, 
	TavernSit, 
	IgnoreDrunkard, 
	ContinueDrinking,
	VisitTavernTable, 
	PickupTorch,
	BurnedToDeath, 
	DontPickupTorch, 
	GoToFireplace,
	declineActions, Retreat,
	DeclineQuest, 
	ApproachDrunkard,
	RobDrunkard, 
	WakeDrunkard, 
	PersistDrunkard, 
	TakeDrunkardHome,
	Conclusion,
	GoToBar, 
	MerchantKill, 
	Interupt,
	Listen,
	AcceptOffer, 
	End, 
	Dungeon, 
	Ending,
	ConfrontBandit,
	ForestPlant, 
	MerchantRetreat,
	AcceptKing,
	Death, 
	DenyKing,
	EndGame, 
	MerchantRetreatActions,
	AcceptKingActions,
	DeathActions,
	DenyKingActions, HelpDrunkard, FountainNo, LeaveBar, acceptActions, ReturnToCity, GoToTavern, ContinueTalking, RetreatAcceptKingCredits, RetreatDeclineOfferCredits, MenuShowCredits, MenuCloseCredits, 
	
}